aplicatie1/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from aplicatie1 import views

app_name = 'carApp'

urlpatterns = [
    path('', views.CarsView.as_view(), name='lista_masini'),
    path('addCar/', views.CreateCarsView.as_view(), name='addCar'),
    path('<int:pk>/updateCar/', views.UpdateCarsView.as_view(), name='updateCar'),
    path('<int:pk>/deleteCar/', views.delete_cars, name='deleteCar'),
    path('<int:pk>/activateCar/', views.activate_cars, name='activateCar'),
    path('inactiveCars', views.CarsInactiveView.as_view(), name='inactiveCars'),
    path('searchCars/', views.search_cars, name='searchCars'),
    path('<int:pk>/CarDetails/', views.CarDetail.as_view(), name='carDetails'),
    path('register/', views.registerPage, name='register'),

    path('diesel/', views.CarsDiesel.as_view(), name='diesel'),
    path('benzina/', views.CarsBenzina.as_view(), name='benzina'),
    path('hybrid/', views.CarsHybrid.as_view(), name='hybrid'),
    path('electric/', views.CarsElectric.as_view(), name='electric'),

    path('mercedes/', views.CarsMercedes.as_view(), name='mercedes'),
    path('audi/', views.CarsAudi.as_view(), name='audi'),
    path('opel/', views.CarsOpel.as_view(), name='opel'),
    path('mazda/', views.CarsMazda.as_view(), name='mazda'),
    path('bmw/', views.CarsBMW.as_view(), name='bmw'),
    path('vw/', views.CarsVW.as_view(), name='vw'),
    path('ford/', views.CarsFord.as_view(), name='ford'),
    path('dacia/', views.CarsDacia.as_view(), name='dacia'),
    path('skoda/', views.CarsSkoda.as_view(), name='skoda'),
    path('seat/', views.CarsSeat.as_view(), name='seat'),
    path('honda/', views.CarsHonda.as_view(), name='honda'),
    path('peugeot/', views.CarsPeugeot.as_view(), name='peugeot'),

    path('motor16/', views.Cars16.as_view(), name='motor16'),
    path('motor18/', views.Cars18.as_view(), name='motor18'),
    path('motor14/', views.Cars14.as_view(), name='motor14'),
    path('motor20/', views.Cars20.as_view(), name='motor20'),
    path('motor22/', views.Cars22.as_view(), name='motor22'),
    path('motor12/', views.Cars12.as_view(), name='motor12'),

    path('automat/', views.CarsAutomata.as_view(), name='automat'),
    path('manual/', views.CarsManuala.as_view(), name='manual'),

    path('rent/', views.rentPage, name='rent'),
    path('inchiriere/', views.inchirierePage, name='inchiriere'),
    path('termeni&conditii/', views.termeniPage, name='termeni&conditii'),
    path('factura/', views.facturaPage, name='factura'),
    path('locatii/', views.locatiiPage, name='locatii'),
]

proiectCars/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from proiectCars import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('cars/', include('aplicatie1.urls')),
    path('locations/', include('aplicatie2.urls')),
    path('userprofile/', include('userprofile.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicatie1/models.py
from django.db import models

# Create your models here.
from aplicatie2.models import Location

MARCA_CHOICES = (
    ('Mercedes', 'MERCEDES'),
    ('Audi', 'AUDI'),
    ('Opel', 'OPEL'),
    ('Mazda', 'MAZDA'),
    ('BMW', 'BMW'),
    ('Volkswagen', 'VOLKSWAGEN'),
    ('Ford', 'FORD'),
    ('Dacia', 'DACIA'),
    ('Skoda', 'SKODA'),
    ('Seat', 'SEAT'),
    ('Honda', 'HONDA'),
    ('Peugeot', 'PEUGEOT'),
)

COMBUSTIBIL_CHOICES = (
    ('DIESEL', 'DIESEL'),
    ('BENZINA', 'BENZINA'),
    ('HYBRID', 'HYBRID'),
    ('ELECTRIC', 'ELECTRIC'),
)

CUTIE_CHOICES = (
    ('AUTOMATA', 'AUTOMATA'),
    ('MANUALA', 'MANUALA'),
)

class Car(models.Model):

    marca = models.CharField(choices=MARCA_CHOICES,max_length=45)
    model = models.CharField(max_length=45)
    an_aparitie = models.IntegerField()
    combustibil = models.CharField(choices=COMBUSTIBIL_CHOICES,max_length=45)
    motorizare = models.FloatField()
    consum = models.FloatField()
    cai_putere = models.IntegerField()
    cutie = models.CharField(choices=CUTIE_CHOICES, max_length=45, null=True, blank=True)
    poza = models.ImageField(upload_to='cars')
    pret = models.CharField(max_length=20)
    active = models.BooleanField(default=1)
    location = models.ForeignKey(Location, on_delete=models.CASCADE,  null=True, blank=True)

    def __str__(self):
        return f"{self.marca} - {self.model} - {self.an_aparitie} - {self.combustibil} - {self.motorizare} - {self.cai_putere} - {self.consum} - {self.pret} "

aplicatie1/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView

# Create your views here.
from aplicatie1.forms import CreateUserForm
from aplicatie1.models import Car

def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form':form}
    return render(request, 'aplicatie1/register.html', context)


def loginPage(request):
    context = {}
    return render(request, 'aplicatie1/login.html', context)

def rentPage(request):
    context = {}
    return render(request, 'aplicatie1/rent.html', context)

def inchirierePage(request):
    context = {}
    return render(request, 'aplicatie1/inchiriere.html', context)

def termeniPage(request):
    context = {}
    return render(request, 'aplicatie1/termeni.html', context)

def facturaPage(request):
    context = {}
    return render(request, 'aplicatie1/factura.html', context)

def locatiiPage(request):
    context = {}
    return render(request, 'aplicatie1/locatii.html', context)

class CarsView(LoginRequiredMixin, ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'


    def get_context_data(self, *args, **kargs):
        data = super(CarsView, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(active=1)
        return data

class CreateCarsView(LoginRequiredMixin, CreateView):
    model = Car
    fields = ['marca', 'model', 'an_aparitie', 'combustibil', 'motorizare', 'consum','cutie', 'cai_putere', 'pret', 'location', 'poza']
    template_name = 'aplicatie1/cars_form.html'


    def get_success_url(self):
        return reverse('carApp:lista_masini')



class UpdateCarsView(LoginRequiredMixin, UpdateView):
    model = Car
    fields = ['marca', 'model', 'an_aparitie', 'combustibil', 'motorizare', 'consum','cutie', 'cai_putere', 'pret','location', 'poza']
    template_name = 'aplicatie1/cars_form.html'

    def get_success_url(self):
        return reverse('carApp:lista_masini')

@login_required
def search_cars(request):
    if request.method == "POST":
        searched = request.POST['searched']
        cars = Car.objects.filter(marca__contains=searched)
        return render(request, 'aplicatie1/search_cars.html', {'searched': searched, 'cars': cars})
    else:
        return render(request, 'aplicatie1/search_cars.html', {})

@login_required
def delete_cars(request, pk):
    Car.objects.filter(id=pk).update(active=0)
    return redirect('carApp:lista_masini')

@login_required
def activate_cars(request, pk):
    Car.objects.filter(id=pk).update(active=1)
    return redirect('carApp:lista_masini')


class CarsInactiveView(LoginRequiredMixin, ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'
    paginate_by = 8
    queryset = model.objects.filter(active=0)
    context_object_name = 'cars'

    def get_context_data(self, *args, **kargs):
        data = super(CarsInactiveView, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(active=0)
        return data

class  CarDetail(LoginRequiredMixin, DetailView):
    model = Car
    template_name = 'aplicatie1/car_detail.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarDetail, self).get_context_data(*args, **kargs)
        data['carsL'] = self.model.objects.filter(active=1)
        return data

class CarsDiesel(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsDiesel, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(combustibil='DIESEL')
        return data

class CarsBenzina(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsBenzina, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(combustibil='BENZINA')
        return data


class CarsHybrid(LoginRequiredMixin, ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsHybrid, self).get_context_data(*args, **kargs)
        data['carsL'] = self.model.objects.filter(combustibil='HYBRID')
        return data


class CarsElectric(LoginRequiredMixin, ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsElectric, self).get_context_data(*args, **kargs)
        data['carsL'] = self.model.objects.filter(combustibil='ELECTRIC')
        return data


class CarsMercedes(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsMercedes, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Mercedes')
        return data

class CarsAudi(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsAudi, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Audi')
        return data

class CarsOpel(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsOpel, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Opel')
        return data

class CarsMazda(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsMazda, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Mazda')
        return data

class CarsBMW(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsBMW, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='BMW')
        return data

class CarsVW(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsVW, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Volkswagen')
        return data

class CarsFord(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsFord, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Ford')
        return data

class CarsDacia(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsDacia, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Dacia')
        return data

class CarsSkoda(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsSkoda, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Skoda')
        return data

class CarsSeat(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsSeat, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Seat')
        return data

class CarsHonda(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsHonda, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Honda')
        return data

class CarsPeugeot(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CarsPeugeot, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(marca='Peugeot')
        return data

class Cars16(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(Cars16, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(motorizare=1.6)
        return data

class Cars18(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(Cars18, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(motorizare=1.8)
        return data

class Cars14(LoginRequiredMixin,ListView):
    model = Car
    template_name = 'aplicatie1/cars_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(Cars14, self).get_context_data( *args, **kargs)
        data['carsL'] = self.model.objects.filter(motorizare=1.4)

templates/aplicatie1/car_detail.html
{% extends 'base.html' %}
{% block content %}


<tbody>

<br/>
{% if request.user.is_superuser is False %}
<div  align="center">
    <h1>{{ object.marca }} {{ object.model }} </h1>
    <h3> Locatie: {{ object.location }} </h3>
<div class="card border-dark md-1" style="max-width: 1300px;" align="left" >
  <div class="card">


  <div class="card-body">
     <div class="card-deck">
  <div class="card bg-light mb-3">

    <div class="card-body">
      <h5 class="card-title">Marca</h5>
<p class="card-text" style="font-size: 26px;"><b>{{ object.marca }}</b></p>    </div>
  </div>
  <div class="card bg-light mb-3">

    <div class="card-body">
      <h5 class="card-title">Model</h5>
<p class="card-text" style="font-size: 26px;"><b>{{ object.model }}</b></p>    </div>
  </div>
  <div class="card bg-light mb-3">
    <div class="card-body">
      <h5 class="card-title">An</h5>
        <p class="card-text" style="font-size: 26px;"><b>{{ object.an_aparitie}}</b></p>
    </div>
  </div>
</div>
      <br>
      <br>
           <div class="card-deck">
  <div class="card bg-light mb-3">

    <div class="card-body">
      <h5 class="card-title">Combustibil</h5>
<p class="card-text" style="font-size: 26px;"><b>{{ object.combustibil }}</b></p>    </div>
  </div>
  <div class="card bg-light mb-3">

    <div class="card-body">
      <h5 class="card-title">Motor</h5>
<p class="card-text" style="font-size: 26px;"><b>{{ object.motorizare }}</b></p>    </div>
  </div>
  <div class="card bg-light mb-3">
    <div class="card-body">
      <h5 class="card-title">Consum</h5>
        <p class="card-text" style="font-size: 26px;"><b>{{ object.consum}}</b></p>
    </div>
  </div>
</div>

            <br>
      <br>
           <div class="card-deck">
  <div class="card bg-light mb-3">

    <div class="card-body">
      <h5 class="card-title">Cutie de viteze</h5>
<p class="card-text" style="font-size: 26px;"><b>{{ object.cutie }}</b></p>    </div>
  </div>
  <div class="card bg-light mb-3">

    <div class="card-body">
      <h5 class="card-title">Cai putere</h5>
<p class="card-text" style="font-size: 26px;"><b>{{ object.cai_putere }}</b></p>    </div>
  </div>
  <div class="card bg-light mb-3">
    <div class="card-body">
      <h5 class="card-title">Pret</h5>
        <p class="card-text" style="font-size: 26px;"><b>{{ object.pret}}</b></p>
    </div>
  </div>
</div>
      <br>
      <br>
           <div align="center"><a class="btn btn-info" href="{% url 'carApp:inchiriere' %}" style="font-size: 26px;">VREAU SA INCHIRIEZ!</a></div>
  </div>
  <img class="card-img-bottom" src="{{ object.poza.url }}" class="img-fluid rounded-start" alt="Card image cap">
</div>
</div>
    </div>
<br>
<div align="center">
<b><a href="{% url 'carApp:lista_masini' %}"><input type="button" value="Back" class="btn btn-success" style="font-size: 20px;" /></a></b>
    </div>
{% endif %}
</tbody>

{% endblock %}

templates/aplicatie1/cars_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
         {% for field in form %}
         <br>
                {% if field.label == 'poster' %}
                    {{ field.label }} <img src="{{ field.poza }}">
                {% else %}
         <div align="center"><b>{{ field.label }} {{ field }} {{ field.errors }}</b></div>
         <br>
         <br>
                {% endif %}
            {% endfor %}
         <br>
        <div align="center"><button class="btn btn-success" type="submit">Save</button></div>
    </form>

{% endblock %}

templates/aplicatie1/cars_index.html
{% extends 'base.html' %}
{% block content %}

<p>
{% if request.user.is_superuser is False %}
<div align="center">
<div class="card-deck" align="center">
             <div class="card text-white bg-dark mb-3 text-center" style="max-width: 49rem;">

    <div class="card-body">
      <h4 class="card-title">MARCI DE MASINI</h4>
                    <h5 class="card-text">Puteti accesa fiecare marca de masina apasand pe butonul cu numele marcii
                        dorite.</h5>
         <br>
                    <a class="btn btn-success" href="{% url 'carApp:mercedes' %}" style="font-size: 20px;">MERCEDES</a>
                    <a class="btn btn-success" href="{% url 'carApp:audi' %}" style="font-size: 20px;">AUDI</a>
                    <a class="btn btn-success" href="{% url 'carApp:opel' %}" style="font-size: 20px;">OPEL</a>
                    <a class="btn btn-success" href="{% url 'carApp:mazda' %}" style="font-size: 20px;">MAZDA</a>
                    <a class="btn btn-success" href="{% url 'carApp:bmw' %}" style="font-size: 20px;">BMW</a>
                            <br>
                    <br>
                    <a class="btn btn-success" href="{% url 'carApp:vw' %}" style="font-size: 20px;">VOLKSWAGEN</a>


                    <a class="btn btn-success" href="{% url 'carApp:ford' %}" style="font-size: 20px;">FORD</a>
                    <a class="btn btn-success" href="{% url 'carApp:dacia' %}" style="font-size: 20px;">DACIA</a>
                    <a class="btn btn-success" href="{% url 'carApp:skoda' %}" style="font-size: 20px;">SKODA</a>
                            <br>
                    <br>
                    <a class="btn btn-success" href="{% url 'carApp:seat' %}" style="font-size: 20px;">SEAT</a>
                    <a class="btn btn-success" href="{% url 'carApp:honda' %}" style="font-size: 20px;">HONDA</a>
                    <a class="btn btn-success" href="{% url 'carApp:peugeot' %}" style="font-size: 20px;">PEUGEOT</a>
                    <a class="btn btn-success" href="{% url 'carApp:lista_masini' %}" style="font-size: 20px;">ALL</a>
                    <br>
                    <br>
    </div>

  </div>
           <div class="card text-white bg-dark mb-3 text-center" style="max-width: 51rem;">

    <div class="card-body">
      <h4 class="card-title">TIPUL COMBUSTIBILULUI</h4>
                    <h5 class="card-text">Puteti accesa masinile care au un anumit tip de combustibil apasand pe butonul
                        cu numele combustibilului dorit.</h5>
                    <br>
                    <br>

                    <a class="btn btn-success" href="{% url 'carApp:diesel' %}" style="font-size: 20px;">DIESEL</a>

                    <a class="btn btn-success" href="{% url 'carApp:benzina' %}" style="font-size: 20px;">BENZINA</a>
                    <br>
                    <br>
                    <a class="btn btn-success" href="{% url 'carApp:hybrid' %}" style="font-size: 20px;">HYBRID</a>

                    <a class="btn btn-success" href="{% url 'carApp:electric' %}" style="font-size: 20px;">ELECTRIC</a>
                    <br>
                    <br>
    </div>

  </div>
           <div class="card text-white bg-dark mb-3 text-center" style="max-width: 51rem;">

    <div class="card-body">
     <h4 class="card-title">CAPACITATE MOTOR</h4>
                    <h5 class="card-text">Puteti accesa masinile care au o anumita capacitate a motorului apasand pe
                        butonul
                        cu motorizarea dorita.</h5>
                    <br>

                    <a class="btn btn-success" href="{% url 'carApp:motor12' %}" style="font-size: 20px;">Motor de 1.2</a>
                    <a class="btn btn-success" href="{% url 'carApp:motor14' %}" style="font-size: 20px;">Motor de 1.4</a>
                <br>
        <br>
                    <a class="btn btn-success" href="{% url 'carApp:motor16' %}" style="font-size: 20px;">Motor de 1.6</a>

                    <a class="btn btn-success" href="{% url 'carApp:motor18' %}" style="font-size: 20px;">Motor de 1.8</a>
                <br>
        <br>
                    <a class="btn btn-success" href="{% url 'carApp:motor20' %}" style="font-size: 20px;">Motor de 2.0</a>
                    <a class="btn btn-success" href="{% url 'carApp:motor22' %}" style="font-size: 20px;">Motor de 2.2</a>
                    <br>
                    <br>
    </div>

  </div>


    <div class="card text-white bg-dark mb-3 text-center" style="max-width: 51rem;">

    <div class="card-body">
     <h4 class="card-title">CUTIE DE VITEZE</h4>
                    <h5 class="card-text">Puteti accesa masinile care au o anumita cutie de viteze apasand pe
                        butonul
                        cu tipul dorit.</h5>
                    <br>
                    <br>

                    <a class="btn btn-success" href="{% url 'carApp:automat' %}" style="font-size: 20px;">Cutie de viteze AUTOMATA</a>
<br>
        <br>
        <br>
                    <a class="btn btn-success" href="{% url 'carApp:manual' %}" style="font-size: 20px;">Cutie de viteze MANUALA</a>

                    <br>
                    <br>
    </div>

  </div>
</div>
</div>

{% endif %}
</p>
<br>
        <table class="table table-bordered table-striped border-black">
            <thead class="thead-dark">
            {% if request.user.is_superuser %}
            <tr>
                <th>Index</th>
                <th>Marca</th>
                <th>Model</th>
                <th>Anul aparitiei</th>
                <th>Tip combustibil</th>
                <th>Motor</th>
                <th>Cai putere (HP)</th>
                <th>Consum</th>
                <th>Cutie de viteze</th>
                <th>Pret</th>
                 <th>ID locatie</th>
                <th>Poza</th>
                <th>Stare</th>
                <th>Actions</th>
            </tr>
            {% endif %}
            </thead>
            <tbody>

            <div class="col-md-12">
                <div class="row">
                    {% for item in carsL %}
                    {% if request.user.is_superuser is False %}
                    <div class="col-md-3">
                        <div class="card" style="width: 35rem;" align="center">
                            <img class="card-img-top" src="{{ item.poza.url }}" alt="Card image cap" width="500"
                                 height="300">
                            <div class="card-body">
                                <h5 class="card-title" style="font-size: 25px;"><b>{{ item.marca }}
                                    {{ item.model }}</b>
                                </h5>
                                <a class="btn btn-success" href="{% url 'carApp:carDetails' item.id %}"
                                   >DETALII</a>
                            </div>

                        </div>
                        <br>
                    </div>


                    {% elif request.user.is_superuser %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.marca }}</td>
                        <td>{{ item.model }}</td>
                        <td>{{ item.an_aparitie }}</td>
                        <td>{{ item.combustibil }}</td>
                        <td>{{ item.motorizare }}</td>
                        <td>{{ item.cai_putere }}</td>
                        <td>{{ item.consum }}</td>
                        <td>{{ item.cutie }}</td>
                        <td>{{ item.pret }}</td>
                        <td>{{ item.location_id }}</td>

                        <td>
                            <img src="{{ item.poza.url }}" width="500" height="300">
                        </td>
                        <td>
                            {% if item.active == 1 %}
                            <span>Active</span>
                            {% else %}
                            <span>Inactive</span>
                            {% endif %}
                        </td>
                        <td><a class="btn btn-success" href="{% url 'carApp:updateCar' item.id %}"
                               >EDITEAZA</a>
                            {% if item.active == 1 %}
                            <br>
                            <br>
                            <a class="btn btn-danger" href="{% url 'carApp:deleteCar' item.id %}"
                               >STERGE</a>
                            <br>
                            <br>
                            {% else %}
                            <a class="btn btn-info" href="{% url 'carApp:activateCar' item.id %}"
                              >ACTIVEAZA</a>
                            <br>
                            <br>
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            </tbody>
        </table>

        {% endblock %}

templates/aplicatie1/search_cars.html
{% extends 'base.html' %}
{% block content %}
    <center>
        {% if searched %}
          <h3>You searched for "{{ searched }}"</h3>
          <h4>We found this: </h4>
            <br/>
            {% for car in cars %}
               <a href="{% url 'carApp:carDetails' car.id %}" style="font-size: 22px;">{{ car.marca }}</a> <br/>
            {% endfor %}
        {% endif %}
    </center>
{% endblock %}