aplicatie1/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from aplicatie1 import views

app_name = 'carApp'

urlpatterns = [
    path('', views.CarsView.as_view(), name='lista_masini'),
    path('addCar/', views.CreateCarsView.as_view(), name='addCar'),
    path('<int:pk>/updateCar/', views.UpdateCarsView.as_view(), name='updateCar'),
    path('<int:pk>/deleteCar/', views.delete_cars, name='deleteCar'),
    path('<int:pk>/activateCar/', views.activate_cars, name='activateCar'),
    path('inactiveCars', views.CarsInactiveView.as_view(), name='inactiveCars'),
    path('searchCars/', views.search_cars, name='searchCars'),
    path('<int:pk>/CarDetails/', views.CarDetail.as_view(), name='carDetails'),
    path('register/', views.registerPage, name='register'),

    path('diesel/', views.CarsDiesel.as_view(), name='diesel'),
    path('benzina/', views.CarsBenzina.as_view(), name='benzina'),
    path('hybrid/', views.CarsHybrid.as_view(), name='hybrid'),
    path('electric/', views.CarsElectric.as_view(), name='electric'),

    path('mercedes/', views.CarsMercedes.as_view(), name='mercedes'),
    path('audi/', views.CarsAudi.as_view(), name='audi'),
    path('opel/', views.CarsOpel.as_view(), name='opel'),
    path('mazda/', views.CarsMazda.as_view(), name='mazda'),
    path('bmw/', views.CarsBMW.as_view(), name='bmw'),
    path('vw/', views.CarsVW.as_view(), name='vw'),
    path('ford/', views.CarsFord.as_view(), name='ford'),
    path('dacia/', views.CarsDacia.as_view(), name='dacia'),
    path('skoda/', views.CarsSkoda.as_view(), name='skoda'),
    path('seat/', views.CarsSeat.as_view(), name='seat'),
    path('honda/', views.CarsHonda.as_view(), name='honda'),
    path('peugeot/', views.CarsPeugeot.as_view(), name='peugeot'),

    path('motor16/', views.Cars16.as_view(), name='motor16'),
    path('motor18/', views.Cars18.as_view(), name='motor18'),
    path('motor14/', views.Cars14.as_view(), name='motor14'),
    path('motor20/', views.Cars20.as_view(), name='motor20'),
    path('motor22/', views.Cars22.as_view(), name='motor22'),
    path('motor12/', views.Cars12.as_view(), name='motor12'),

    path('automat/', views.CarsAutomata.as_view(), name='automat'),
    path('manual/', views.CarsManuala.as_view(), name='manual'),

    path('rent/', views.rentPage, name='rent'),
    path('inchiriere/', views.inchirierePage, name='inchiriere'),
    path('termeni&conditii/', views.termeniPage, name='termeni&conditii'),
    path('factura/', views.facturaPage, name='factura'),
    path('locatii/', views.locatiiPage, name='locatii'),
]

aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('add/', views.CreateLocationView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
    path('locatii_inactive', views.LocationInactiveView.as_view(), name='locatii_inactive')
]

proiectCars/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from proiectCars import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('cars/', include('aplicatie1.urls')),
    path('locations/', include('aplicatie2.urls')),
    path('userprofile/', include('userprofile.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicatie2/models.py
from django.db import models

# Create your models here.

class Location(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city}"

aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from aplicatie2.models import Location


class LocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie2/location_index.html'
    queryset = model.objects.filter(active=1)
    context_object_name = 'locations'

    def get_context_data(self,  *args, **kargs):
        data = super(LocationView, self).get_context_data( *args, **kargs)
        data['locations'] = self.model.objects.filter(active=1)
        return data

class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Location
    # fields = '__all__'
    fields = ['city', 'country']
    template_name = 'aplicatie2/location_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')

class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'aplicatie2/location_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')

@login_required
def delete_location(request, pk):
    Location.objects.filter(id=pk).update(active=0)
    return redirect('locations:lista_locatii')

@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=1)
    return redirect('locations:lista_locatii')

class LocationInactiveView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie2/location_index.html'
    queryset = model.objects.filter(active=0)
    context_object_name = 'locations'

    def get_context_data(self, *args, **kargs):
        data = super(LocationInactiveView, self).get_context_data( *args, **kargs)
        data['locations'] = self.model.objects.filter(active=0)
        return data

templates/aplicatie2/location_form.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <BR>
    <BR>
    <BR>
    <BR>
    <div align="center"><b>{{ field.label }} : {{ field }} {{ field.errors }}</b></div>
     <br>
         <br>
    {% endfor %}
    <div align="center"><button class="btn btn-success" type="submit">Salveaza!</button></div>
</form>
{% endblock %}

templates/aplicatie2/location_index.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
    <table class="table table-striped">
  <thead class="thead-dark">
            <tr>
                <th>Index</th>
                <th>City</th>
                <th>Country</th>
                <th>Stare</th>
                 <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in locations %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.city }}</td>
                    <td>{{ item.country }}</td>
                    <td>{% if item.active == 1 %}
                            <span>Activ</span>
                        {% else %}
                        <span>Inactiv</span>
                        {% endif %}
                    </td>

                    <td><a href="{% url 'locations:modifica' item.id%}" class="btn btn-success">Modifica</a>
                        {% if item.active == 1%}
                        <a href="{% url 'locations:sterge' item.id%}" class="btn btn-danger">Sterge</a>
                        {% else %}
                        <a href="{% url 'locations:activeaza' item.id%}" class="btn btn-info">Activeaza</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
            {% else %}
                <li><a class="disabled btn" ><span><<</span></a></li>
            {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active btn btn-warningpy"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
            {% else %}
                <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a class="btn" href="?page={{ page_obj.next_page_number}}">>></a></li>
        {% else %}
            <li class="disabled btn"><span>>></span></li>
        {% endif %}
        <span class="align-right">Showing {{ page_obj.start_index}} - {{ page_obj.end_index}} of {{ page_obj.paginator.count}}</span>
        </ul>
    {% endif %}
{% endblock %}