aplicatie1/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from aplicatie1 import views

app_name = 'carApp'

urlpatterns = [
    path('', views.CarsView.as_view(), name='lista_masini'),
    path('addCar/', views.CreateCarsView.as_view(), name='addCar'),
    path('<int:pk>/updateCar/', views.UpdateCarsView.as_view(), name='updateCar'),
    path('<int:pk>/deleteCar/', views.delete_cars, name='deleteCar'),
    path('<int:pk>/activateCar/', views.activate_cars, name='activateCar'),
    path('inactiveCars', views.CarsInactiveView.as_view(), name='inactiveCars'),
    path('searchCars/', views.search_cars, name='searchCars'),
    path('<int:pk>/CarDetails/', views.CarDetail.as_view(), name='carDetails'),
    path('register/', views.registerPage, name='register'),

    path('diesel/', views.CarsDiesel.as_view(), name='diesel'),
    path('benzina/', views.CarsBenzina.as_view(), name='benzina'),
    path('hybrid/', views.CarsHybrid.as_view(), name='hybrid'),
    path('electric/', views.CarsElectric.as_view(), name='electric'),

    path('mercedes/', views.CarsMercedes.as_view(), name='mercedes'),
    path('audi/', views.CarsAudi.as_view(), name='audi'),
    path('opel/', views.CarsOpel.as_view(), name='opel'),
    path('mazda/', views.CarsMazda.as_view(), name='mazda'),
    path('bmw/', views.CarsBMW.as_view(), name='bmw'),
    path('vw/', views.CarsVW.as_view(), name='vw'),
    path('ford/', views.CarsFord.as_view(), name='ford'),
    path('dacia/', views.CarsDacia.as_view(), name='dacia'),
    path('skoda/', views.CarsSkoda.as_view(), name='skoda'),
    path('seat/', views.CarsSeat.as_view(), name='seat'),
    path('honda/', views.CarsHonda.as_view(), name='honda'),
    path('peugeot/', views.CarsPeugeot.as_view(), name='peugeot'),

    path('motor16/', views.Cars16.as_view(), name='motor16'),
    path('motor18/', views.Cars18.as_view(), name='motor18'),
    path('motor14/', views.Cars14.as_view(), name='motor14'),
    path('motor20/', views.Cars20.as_view(), name='motor20'),
    path('motor22/', views.Cars22.as_view(), name='motor22'),
    path('motor12/', views.Cars12.as_view(), name='motor12'),

    path('automat/', views.CarsAutomata.as_view(), name='automat'),
    path('manual/', views.CarsManuala.as_view(), name='manual'),

    path('rent/', views.rentPage, name='rent'),
    path('inchiriere/', views.inchirierePage, name='inchiriere'),
    path('termeni&conditii/', views.termeniPage, name='termeni&conditii'),
    path('factura/', views.facturaPage, name='factura'),
    path('locatii/', views.locatiiPage, name='locatii'),
]

aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('add/', views.CreateLocationView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
    path('locatii_inactive', views.LocationInactiveView.as_view(), name='locatii_inactive')
]

proiectCars/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from proiectCars import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('cars/', include('aplicatie1.urls')),
    path('locations/', include('aplicatie2.urls')),
    path('userprofile/', include('userprofile.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<html>
<head>

    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
</head>
<body style="background-color:">
<div class="container-fluid">
    <div class="row">
        <div class="col col-lg-13">
            <header class="header">
                <nav class="navbar navbar-light" style="background-color: #84e184;">
                    <span></span>
                    <a class="navbar-brand" style="font-size:30px; color:BLACK;"><b>AUTOMOTIVE - MASINI DE INCHIRIAT</b></a>
                    {% if request.user.is_superuser %}
                    <a class="btn  btn-outline-dark" href="{% url 'carApp:lista_masini' %}"
                      >ACTIVE CARS</a>
                    <br>
                    <br>
                    <br>
                    <a class="btn  btn-outline-dark " href="{% url 'carApp:inactiveCars' %}"
                     >INACTIVE CARS</a>
                    <br>
                    <br>
                    <br>
                    <a class="btn btn-outline-dark" href="{% url 'carApp:addCar' %}"
                      >ADD CAR</a>
                    <br>
                    <br>
                    <br>
                    <a class="btn btn-outline-dark" href="{% url 'locations:lista_locatii' %}"
                      >LOCATII ACTIVE </a>
                    <br>
                    <br>
                    <br>
                    <a class="btn btn-outline-dark" href="{% url 'locations:locatii_inactive' %}"
                      >LOCATII INACTIVE</a>
                    <br>
                    <br>
                    <br>
                     <a id="id_adaugare" class="btn btn-outline-dark" href="{% url 'locations:add' %}">ADAUGA LOCATIE</a>
                    <br>
                    <br>
                    <br>
                    <a class="btn  btn-outline-dark" href="/admin">ADMIN</a>
                    <br>
                    <br>
                    <br>
                    {% endif %}
                    {% if request.user.is_authenticated is False %}
                    <a class="btn btn-outline-dark" href="{% url 'login' %}">LOGIN</a>
                    <a class="btn btn-outline-dark" href="{% url 'carApp:register' %}">REGISTER</a>
                    {% elif request.user.is_authenticated %}
                    {% if request.user.is_superuser is False%}
                    <a class="btn btn-outline-dark" href="{% url 'carApp:termeni&conditii' %}"
                       >TERMENI SI CONDITII</a>
                     <a class="btn btn-outline-dark" href="{% url 'carApp:locatii' %}"
                      >UNDE NE GASITI?</a>
                    {% endif %}
                    <form class="form-inline my-2 my-lg-0" method="POST"
                          action="{% url 'carApp:searchCars' %}">
                        {% csrf_token %}
                        <input type="search" class="form-control mr-sm-3" placeholder="Cauta o marca"
                               aria-label="Search" name="searched" aria-describedby="search-addon"
                               />
                        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit"
                              > SEARCH
                        </button>
                    </form>

                    <a class="btn btn-outline-dark" href="{% url 'logout' %}"
                       >LOGOUT</a>
                    {% endif %}
                    <br>
                    <br>
                    <br>


                </nav>
            </header>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}

</body>
</html>